SAVING_IMAGES_STEPS = True
VERBOSE = True
LINES_DISTANCE_THRESHOLD = 50
LINES_ENDPOINTS_DIFFERENCE = 10
THRESHOLD_MIN = 160
THRESHOLD_MAX = 255
GAUSSIAN_BLUR_KERNEL = (11, 11)
NOTE_PITCH_DETECTION_MIDDLE_SNAPPING = 6

# Key extractor:
KEY_WIDTH_DIVIDER = 40
# WINDOW_WIDTH = 50
WHITE_PIXELS_PERCENTAGE = 0.85
WINDOW_SHIFT = 2
